## Append samples you want in your CSV to this file as resources ##
resources:
- managed-gitops_v1alpha1_gitopsdeployment.yaml
- managed-gitops_v1alpha1_gitopsdeploymentsyncrun.yaml
- managed-gitops_v1alpha1_gitopsdeploymentrepositorycredential.yaml
- managed-gitops.redhat.com_v1alpha1_gitopsdeploymentmanagedenvironment.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
