apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- managed-gitops-appstudio-controller-deployment.yaml
- managed-gitops-backend-deployment.yaml
- managed-gitops-clusteragent-deployment.yaml
